### ISSUE TITLE
Admin Sign Up Route Multiple HTTP responses sent

### ISSUE THREAD

**Issue by mrgjune** [codeforsanjose/e-immigrate#147]
in routes/admin post to / that creates a new admin user the case a failed create of the Admin object is not handled correctly. Currently, it is doing a HTTP response.status(500).json to inform the caller of the problem but has already responded with a success by the time this code is ever executed. Currently, we are responding with success before the create promise is resolved. Express will complain if this code is executed.

**Comment by JMStudiosJoe** [comment]
Feel free to fix if you have the bandwidth :)

**Comment by ginaCFSJ** [comment]
Anyone is working on this one? Or completed? :)
